name: Delete Releases

on: 
  workflow_dispatch:
    inputs:
      tagPattern:
        description: 'Tag pattern'     
        required: true
        default: 'v1'

jobs:
  delete:
    name: Delete
    runs-on: windows-latest
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    
    permissions: write-all
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Delete
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 0
        delete_tags: true
        delete_tag_pattern: ${{ github.event.inputs.tagPattern }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
